---
version: 0.2

phases:
  pre_build:
    commands:
      - echo "Installing additional YUM & Python packages..."
      - yum -y update && yum -y install unzip curl python3-pip
      - pip3 install awscli
      - echo "Installing Packer..."
      - cd /usr/local/bin/ && curl -qL -o packer.zip https://releases.hashicorp.com/packer/1.6.6/packer_1.6.6_linux_amd64.zip && unzip packer.zip
      - cd $CODEBUILD_SRC_DIR/xilinx-u30-ami_base && packer version
      - echo "Validating packer JSON"
      - packer validate xilinx-vt-al2-eks.yml
      - env
      - echo $HOME
  build:
    commands:
      - echo "Build Phase"
      - export AWS_MAX_ATTEMPTS=200
      - cd $CODEBUILD_SRC_DIR/nvidia-efa-ami_base && packer build xilinx-vt-al2-ecs.yml
